export * from './belbin';
export * from './darktriad';
export * from './genos';
export * from './disc';
export * from './setgel';
export * from './empathy';
export * from './narc';
export * from './single';
export * from './holland';
